### ISSUE TITLE
.dll location 32 bits vs 64 bits

### ISSUE THREAD

**Issue by ImperatorS79** [dhewg/nine#11]
On windows 32 bits, 32 bits dll's go to system32. 
On windows 64 bits, 32 bits dll's go to syswow64, and 64 bits dll's to system32.

So it seems that nine-install.sh is wrong.

**Comment by dhewg** [comment]
Note the usage of `wine` vs. `wine64` in there:
````
$ wine winepath -u 'c:\windows\system32'
/home/andre/.wine/dosdevices/c:/windows/syswow64
$ wine64 winepath -u 'c:\windows\system32'
/home/andre/.wine/dosdevices/c:/windows/system32
````
Files get copied to their correct location, and 32bit as well as 64bit DX9 games do work ;)

**Comment by ImperatorS79** [comment]
OK then ^^
