### ISSUE TITLE
Some more packages for Debian buster

### ISSUE THREAD

**Issue by nmr8** [dhewg/nine#2]
I found I needed a few more packages on Debian testing (buster),

```
sudo apt-get install libc6-dev wine64-tools libwine-dev libd3dadapter9-mesa-dev libx11-dev libx11-xcb-dev libxcb1-dev libxcb-dri3-dev libxcb-present-dev libxcb-xfixes0-dev libgl1-mesa-dev libegl1-mesa-dev
sudo apt-get install meson
sudo apt-get install wine-development
sudo apt-get install wine64-development-tools 
sudo apt-get install wine-devel-dev 
sudo apt-get install libwine-development-dev 
sudo apt-get install libwine-dev
sudo apt-get install libc:i386
sudo apt-get install libc6-dev:i386
sudo apt-get install libc6-dev-i386
sudo apt-get install libc6-amd64-i386-cross 
sudo apt-get install wine-devel-dev 
sudo apt-get install libwine-development-dev:i386
sudo apt-get install libd3dadapter9-mesa-dev libd3dadapter9-mesa-dev:i386
sudo apt-get install libdrm-dev libdrm-dev:i386
sudo apt-get install libx11-xcb-dev:i386
sudo apt-get install libxcb-dri3-dev:i386
sudo apt-get install libxcb-present-dev:i386
sudo apt-get install libgl-dev:i386
sudo apt-get install libegl1-mesa-dev:i386 libegl1-mesa-dev
```

Some are not necessary, but I'm not sure which ones ;)

I'm using the winehq Debian builds, so I may have multiple sources for some dependencies. I've attached `dpkg -l \*wine\*` if that's informative.

```
ii  dxvk-wine32-development:i386  0.94+ds1-1     i386         Vulkan-based translation layer for Direct3D 10/11 - wine32 build
ii  dxvk-wine64-development       0.94+ds1-1     amd64        Vulkan-based translation layer for Direct3D 10/11 - wine64 build
ii  fonts-wine                    4.0~rc4-2      all          Windows API implementation - fonts
ii  libkwineffects11              4:5.14.3-2+b1  amd64        KDE window manager effects library
ii  libwine:amd64                 4.0~rc4-2      amd64        Windows API implementation - library
ii  libwine:i386                  4.0~rc4-2      i386         Windows API implementation - library
ii  libwine-dev:amd64             4.0~rc4-2      amd64        Windows API implementation - development files
ii  libwine-development:amd64     3.21-2         amd64        Windows API implementation - library
ii  libwine-development:i386      3.21-2         i386         Windows API implementation - library
ii  libwine-development-dev:amd64 3.21-2         amd64        Windows API implementation - development files
ii  libwine-development-dev:i386  3.21-2         i386         Windows API implementation - development files
ii  wine-devel-amd64              4.0~rc5~buster amd64        WINE Is Not An Emulator - runs MS Windows programs
ii  wine-devel-dev                4.0~rc5~buster amd64        WINE Is Not An Emulator - runs MS Windows programs
ii  wine-devel-i386:i386          4.0~rc5~buster i386         WINE Is Not An Emulator - runs MS Windows programs
ii  wine-development              3.21-2         all          Windows API implementation - standard suite
ii  wine-staging                  4.0~rc5~buster amd64        WINE Is Not An Emulator - runs MS Windows programs
ii  wine-staging-amd64            4.0~rc5~buster amd64        WINE Is Not An Emulator - runs MS Windows programs
ii  wine-staging-i386:i386        4.0~rc5~buster i386         WINE Is Not An Emulator - runs MS Windows programs
ii  wine32:i386                   4.0~rc4-2      i386         Windows API implementation - 32-bit binary loader
ii  wine32-development:i386       3.21-2         i386         Windows API implementation - 32-bit binary loader
ii  wine64                        4.0~rc4-2      amd64        Windows API implementation - 64-bit binary loader
ii  wine64-development            3.21-2         amd64        Windows API implementation - 64-bit binary loader
ii  wine64-development-tools      3.21-2         amd64        Windows API implementation - 64-bit developer tools
ii  wine64-tools                  4.0~rc4-2      amd64        Windows API implementation - 64-bit developer tools
ii  winetricks                    0.0+20181203-3 all          simple tool to work around common problems in Wine
```

**Comment by nmr8** [comment]
FWIW I tried the built nine on a Path of Exile installed and admgpu crashed about 10s after starting (and failed to reset.) Install seemed to work fine.

**Comment by dhewg** [comment]
> 0009:err:module:import_dll Loading library d3dcompiler_47.dll (which is needed by L"C:\\windows\\system32\\d3dx9_42.dll") failed (error c000007b).

That sounds you need a `winetricks d3dcompiler_43`

I think `dxgi.dll` is a DX10/11 library, DXVK has its own too.

But the amdgpu crash shouldn't happen at all, you might want to report that to the kernel/dri.

**Comment by nmr8** [comment]
> That sounds you need a winetricks d3dcompiler_47

Tried that, crash persists about 5-10s after loading Lionseye something.

> I think dxgi.dll is a DX10/11 library, DXVK has its own too.

Yeah, I had initially tried to get DXVK working, left the dlls in place, but PoE is explicitly configured to use d3d9. 

> But the amdgpu crash shouldn't happen at all, you might want to report that to the kernel/dri.

I'll look into it, tough to know what to do as there is virtually nothing in dmesg.

**Comment by dhewg** [comment]
To me it looks like the PoE issue is something independent of nine, does it work without it? If not it's unlikely it will work with nine, and more likely it requires some additional dependencies.

**Comment by dhewg** [comment]
Going through your package list, you got quite some wine versions:
````
wine64 wine32:i386 - stable from debian
wine64-development wine32-development:i386 - development from debian
wine-devel-amd64  wine-devel-i386:i386 - development from winehq
wine-staging-amd64 wine-staging-i386:i386 - staging from winehq
````

Sure that's sufficient? :P

You only require one WINE version with the -dev packages to build nine. So you can get rid of `libwine-development-dev:amd64 libwine-development-dev:i386 wine-devel-dev wine64-development-tools`, but you're missing `libwine-dev:i386`. Nine compiled against the rest should work with all your WINE versions then.

But I'll update the README with a few packages of your list which are missing there, thanks!

**Comment by nmr8** [comment]
> To me it looks like the PoE issue is something independent of nine, does it work without it? If not it's unlikely it will work with nine, and more likely it requires some additional dependencies.

Yeah, it crashes with Mesa's d3d9 implementation as well, you're right.

**Comment by dhewg** [comment]
Dunno if it's the same issue, but there's [this bug report](https://bugs.freedesktop.org/show_bug.cgi?id=104362)
