### ISSUE TITLE
0009:err:ninecfg:nine_set Failed to write 'HKCU\Software\Wine\DllOverrides\d3d9'

### ISSUE THREAD

**Issue by chewi** [dhewg/nine#5]
The above error happens if the HKCU\Software\Wine\DllOverrides key hasn't been created yet. It isn't there in a fresh Wine prefix.

**Comment by chewi** [comment]
Turns out this was easier to fix than I thought!

**Comment by dhewg** [comment]
Hm, I'm pretty sure I tested with a fresh WINE prefix... but the fix looks easy, enough, thanks!
